#emotion metadata
TRAIN_SIZE_EMOTION = 20097
VALIDATION_SIZE_EMOTION = 8612 #0.3*28709(Original train size)
DATASET_SIZE_EMOTION = 35887
ORIG_NUM_CLASSES_EMOTION = 7
PICTURE_DIM_EMOTION = 48
DATASET_PATH_EMOTION = "../datasets/emotions/fer2013/"
DATASET_NAME_EMOTION = "fer2013"

FIN_TRAIN_SIZE_EMOTION = 21970
FIN_VALIDATION_SIZE_EMOTION = 9198
FIN_TEST_SIZE_EMOTION = 7830

emotion = { 0:'Angry', 1:'Disgust', 2: 'Fear', 3: 'Happy',
           4: 'Sad', 5: 'Surprise', 6: 'Neutral', 7: 'Pain'}

#pain metadata
TRAIN_SIZE_PAIN = 26859
TRAIN_SIZE_PAIN_GEATER_2 = 1873
VALIDATION_SIZE_PAIN = 9541
VALIDATION_SIZE_PAIN_GEATER_2 = 586
TEST_SIZE_PAIN = 9753
TEST_SIZE_PAIN_GEATER_2 = 652
ORIG_NUM_CLASSES_PAIN = 16
PIC_DIM_PAIN = 160
PICTURE_DIM_PAIN_H = 160
PICTURE_DIM_PAIN_W = 160
DATASET_PATH_PAIN = "../datasets/pain/pain_organized_ds/"
DATASET_NAME_PAIN = "pain_ds"

#sr metadata
DATASET_PATH_PAIN_SR_HR = "../datasets/pain/"
DATASET_SIZE_SR_HR = 8500
TRAIN_SIZE_SR_HR = 5950
VALIDATION_SIZE_SR_HR = 1690
TEST_SIZE_SR_HR = 843
VALIDATION_SIZE_SR_HR_norm = 1700
TEST_SIZE_SR_HR_norm = 850
ALL_FEATURES_NUM = 156
SR_CARDIOLOGY_FEATURE_NUM = 41
SR_FEATURE_NUM = 3
DATASET_NAME_SR = "GSR_ds"
DATASET_NAME_SR_NORMALIZED = "GSR_ds_normalized"
DATASET_NAME_SR_ELECTROCARDIOLOGY = "SR_cardiography"
DATASET_ALL_FEATURES = "All_features"

#classes metadata
NUM_CLASSES_EMOTION = 8
NUM_CLASSES_PAIN=13
NUM_CLASSES_SR = 5